### PR TITLE
Prevent thread safety issue and improve loading operations to be async

### PR DESCRIPTION
**Pull request by jdemaris**
I encountered a number of issues with expostal inside of a larger application environment, but since the bones are so solid here I decided to refactor it to clean it up and resolve all of the issues. This does change the API (this was a necessary change - not purely stylistic), so I recommended increasing at least the minor version number as well (proposed is 0.2.0).

**Issue 1: Backgrounding the First Load**
As the system was set up, there was no way to set up my application so that the first, slow call to libpostal could happen in a background process. Any attempts to do so (spawn, genstage, genstage wrapping another genstage) all just caused the entire BEAM to hang while it loaded up.

The root cause for this was that the slow process was actually happening inside of the "load" function of the NIF, which executes in the global BEAM context instead of a single process. In order to make it "backgroundable" we needed the NIF to load first, and then a call to this slow process to happen within the normal scheduling system of Erlang which would allow other processes (e.g. the IEx foreground) to continue responding normally.

**Issue 2: the Slow Initial Load breaks the Erlang scheduler**
All NIF functions should return in under 20 milliseconds (https://medium.com/@jlouis666/erlang-dirty-scheduler-overhead-6e1219dcc7). If they do not, then it really starts messing up the BEAM schedulers. Fortunately, there was a recent introduction of Dirty Schedulers, and these are enabled by default in all OTP 20 / Elixir 1.4.5 builds. To make sure that anything that might call the slow initialization function makes use of this, I have added `ERL_NIF_DIRTY_JOB_IO_BOUND` to the ErlNifFunc definitions. To preserve backward compatibility, I have made this optional. If the user is running an older version of OTP (e.g. 18) it will not add this flag, since the NIF API doesn't support it.

Additionally, to make this bootstrap process something that can be launched in a background process without having to include a dummy address to parse, I extracted this load functionality out into it's own `bootstrap` function. You do not have to call it explicitly if you don't want to, but be aware that if you don't, then the first call to `expand_address` or `parse_address` will be slow. If you do want to call it, you can have your Mix application spawn it into the background on start:

```
spawn(fn -> Expostal.bootstrap end)
```

**Issue 3: libpostal is not thread safe**
So the upstream library, libpostal, is not actually threadsafe (see https://github.com/openvenues/libpostal/issues/34). This does not present itself as a problem during basic testing with IEx since (a) its been blocking on the initial load and (b) after the initial load it's so fast that you would never accidentally cause a race. Unfortunately, if you start setting up tests using `Flow` or any other larger scale system, it's relatively easy to accidentally cause a segfault from two different calls to `parse_address/1` at the same time. This actually causes a segmentation fault in libpostal and crashes the entire BEAM.

To resolve this, I added a mutex around the setup and around the calls to parse_address and expand_address to make sure that only one is executing at any given moment. Unfortunately, since there is internally shared state in libpostal between expanding and parsing, this meant that we can't have separate NIFs for Expander and Parser - because then they can't share a mutex lock! This was what caused me to refactor them into a single expostal.c and expostal.ex.

**Conclusion**
With these changes, we can load the library smoothly in the background during startup, prevent hanging IEx (or real applications) on load and prevent race conditions in libpostal from affecting the stability of our applications.

### CODE REVIEW

**Comment by jdemaris** [comment]
I see that the build is failing because the official Elixir 1.4.5 Docker image is running an ancient OTP 18. Looking into getting that fixed now.

**Comment by xiamx** [comment]
Thanks @jdemaris looks very elaborate!
I've tried to make travis-ci use otp 20 in this https://travis-ci.org/SweetIQ/expostal/builds/251299854?utm_source=github_status&utm_medium=notification Let's see if it's going to work.

**Comment by jdemaris** [comment]
@xiamx I got it working on pre-OTP 20 as well! It is now backward compatible and shouldn't cause any issues on older versions of Elixir / Erlang either.

**Comment by xiamx** [comment]
Thanks @jdemaris  this is awesome

**Comment by xiamx** [comment]
v0.2.0 is release 🎉

**Pull request merged**
